/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODER.Voucher;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
public class KhuyenMai extends javax.swing.JFrame {
      private VoucherService ss = new VoucherService();
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<Voucher> listKM = new ArrayList<>();
    private int index = -1;
    /**
     * Creates new form KhuyenMai
     */
    public KhuyenMai() {
        initComponents();
        
        
    }
     private void fillTable(List<Voucher> m) {
        dtm = (DefaultTableModel) tblQLPGG.getModel();
        dtm.setRowCount(0);
        for (Voucher x : m) {
            dtm.addRow(x.toDataRow());
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        cboLoaiGiamInsert = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGtriAD = new javax.swing.JTextField();
        dataTuNgay = new com.toedter.calendar.JDateChooser();
        dataDenNgay = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        LamMoiForm = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLPGG = new javax.swing.JTable();
        txtTimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lamMoiTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ PHIẾU GIẢM GIÁ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã voucher: ");

        jLabel2.setText("Loại giảm giá: ");

        jLabel3.setText("Tên voucher: ");

        cboLoaiGiamInsert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dành Cho Khách Hàng", "Dành Cho Tất Cả" }));
        cboLoaiGiamInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiGiamInsertActionPerformed(evt);
            }
        });

        jLabel5.setText("Giá trị được áp dụng (%) : ");

        jLabel6.setText("Ngày bắt đầu: ");

        jLabel7.setText("Ngày kết thúc: ");

        dataTuNgay.setDateFormatString("yyyy-MM-dd");

        dataDenNgay.setDateFormatString("yyyy-MM-dd");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        LamMoiForm.setText("Làm mới");
        LamMoiForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamMoiFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LamMoiForm, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnThem)
                .addGap(27, 27, 27)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(LamMoiForm)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLoaiGiamInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtMa))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataDenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtTen)
                    .addComponent(txtGtriAD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dataTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cboLoaiGiamInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtGtriAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dataDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu giảm giá", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel8.setText("Tìm kiếm theo mã: ");

        tblQLPGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Tên", "Loại giảm", "Giá trị được áp dụng", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        tblQLPGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLPGGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLPGG);

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lamMoiTable.setText("Làm mới");
        lamMoiTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(lamMoiTable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lamMoiTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiGiamInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiGiamInsertActionPerformed
        // TODO add your handling code here:
                                                       
    // Lấy loại giảm giá được chọn từ ComboBox
    String loaiGiam = (String) cboLoaiGiamInsert.getSelectedItem();
    
    // Xử lý tùy thuộc vào loại giảm giá
    // Ví dụ: Cập nhật giao diện hoặc thực hiện hành động tương ứng
    if (loaiGiam != null) {
        // Nếu loại giảm giá là "Dành Cho Khách Hàng", thực hiện một số hành động
        if (loaiGiam.equals("Dành Cho Khách Hàng")) {
            // Thực hiện hành động cần thiết cho loại giảm giá này
        } else if (loaiGiam.equals("Dành Cho Tất Cả")) {
            // Thực hiện hành động cần thiết cho loại giảm giá này
        }
    }
                                                 

    }//GEN-LAST:event_cboLoaiGiamInsertActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
                                             
    String maVoucher = txtMa.getText();
    String tenVoucher = txtTen.getText();
    String loaiGiam = (String) cboLoaiGiamInsert.getSelectedItem();
    String giaTriAD = txtGtriAD.getText();
    java.util.Date tuNgay = dataTuNgay.getDate();
    java.util.Date denNgay = dataDenNgay.getDate();

    // Thực hiện kiểm tra dữ liệu
    if (maVoucher.isEmpty() || tenVoucher.isEmpty() || giaTriAD.isEmpty() || tuNgay == null || denNgay == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Chuyển đổi dữ liệu ngày
    java.sql.Date sqlTuNgay = new java.sql.Date(tuNgay.getTime());
    java.sql.Date sqlDenNgay = new java.sql.Date(denNgay.getTime());

    // Thực hiện thêm vào cơ sở dữ liệu (thay đổi theo cách bạn lưu trữ dữ liệu)
    try {
        // Giả sử bạn có một phương thức để thêm voucher vào cơ sở dữ liệu
        // addVoucher(maVoucher, tenVoucher, loaiGiam, giaTriAD, sqlTuNgay, sqlDenNgay);
        JOptionPane.showMessageDialog(this, "Thêm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        // Cập nhật bảng nếu cần
        // loadTableData();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm voucher: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
 
    
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
                                            
    // Lấy dữ liệu từ các trường nhập liệu
    String maVoucher = txtMa.getText();
    String tenVoucher = txtTen.getText();
    String loaiGiam = (String) cboLoaiGiamInsert.getSelectedItem();
    String giaTriAD = txtGtriAD.getText();
    java.util.Date tuNgay = dataTuNgay.getDate();
    java.util.Date denNgay = dataDenNgay.getDate();

    // Thực hiện kiểm tra dữ liệu
    if (maVoucher.isEmpty() || tenVoucher.isEmpty() || giaTriAD.isEmpty() || tuNgay == null || denNgay == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Chuyển đổi dữ liệu ngày
    java.sql.Date sqlTuNgay = new java.sql.Date(tuNgay.getTime());
    java.sql.Date sqlDenNgay = new java.sql.Date(denNgay.getTime());

    // Thực hiện cập nhật cơ sở dữ liệu (thay đổi theo cách bạn lưu trữ dữ liệu)
    try {
        // Giả sử bạn có một phương thức để cập nhật voucher
        // updateVoucher(maVoucher, tenVoucher, loaiGiam, giaTriAD, sqlTuNgay, sqlDenNgay);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        // Cập nhật bảng nếu cần
        // loadTableData();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật voucher: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }


        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void LamMoiFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamMoiFormActionPerformed
        txtMa.setText("");
        txtTen.setText("");
        txtGtriAD.setText("");
        dataTuNgay.setDate(null);
        dataDenNgay.setDate(null);
    }//GEN-LAST:event_LamMoiFormActionPerformed

    private void tblQLPGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLPGGMouseClicked
        // TODO add your handling code here:
        int row = tblQLPGG.getSelectedRow();
     
    
    if (row >= 0) {
        // Lấy dữ liệu từ các cột của hàng được chọn
        String maVoucher = tblQLPGG.getValueAt(row, 1).toString(); // Cột mã voucher
        String tenVoucher = tblQLPGG.getValueAt(row, 2).toString(); // Cột tên voucher
        String loaiGiam = tblQLPGG.getValueAt(row, 3).toString(); // Cột loại giảm giá
        String giaTriAD = tblQLPGG.getValueAt(row, 4).toString(); // Cột giá trị được áp dụng
        String ngayBatDau = tblQLPGG.getValueAt(row, 5).toString(); // Cột ngày bắt đầu
        String ngayKetThuc = tblQLPGG.getValueAt(row, 6).toString(); // Cột ngày kết thúc
        
        // Cập nhật các trường nhập liệu trên giao diện
        txtMa.setText(maVoucher);
        txtTen.setText(tenVoucher);
        cboLoaiGiamInsert.setSelectedItem(loaiGiam);
        txtGtriAD.setText(giaTriAD);
        
        // Chuyển đổi chuỗi ngày thành kiểu Date
        try {
            java.util.Date tuNgay = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(ngayBatDau);
            java.util.Date denNgay = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(ngayKetThuc);
            dataTuNgay.setDate(tuNgay);
            dataDenNgay.setDate(denNgay);
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
    }


    }//GEN-LAST:event_tblQLPGGMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                                
    String maVoucher = txtTimkiem.getText();

    if (maVoucher.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã voucher để tìm kiếm.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Giả sử bạn có một phương thức để tìm kiếm voucher
        // List<Voucher> vouchers = searchVoucher(maVoucher);
        // Hiển thị kết quả tìm kiếm trong bảng
        // updateTableData(vouchers);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lamMoiTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamMoiTableActionPerformed
                                                
    String maVoucher = txtTimkiem.getText();

    if (maVoucher.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã voucher để tìm kiếm.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Giả sử bạn có một phương thức để tìm kiếm voucher
        // List<Voucher> vouchers = searchVoucher(maVoucher);
        // Hiển thị kết quả tìm kiếm trong bảng
        // updateTableData(vouchers);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_lamMoiTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuyenMai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LamMoiForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboLoaiGiamInsert;
    private com.toedter.calendar.JDateChooser dataDenNgay;
    private com.toedter.calendar.JDateChooser dataTuNgay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoiTable;
    private javax.swing.JTable tblQLPGG;
    private javax.swing.JTextField txtGtriAD;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables

    private static class VoucherService {

        public VoucherService() {
        }
    }
}
